import type { Metadata } from "next"; // Import type for metadata (like title, description)
import { lora, rubik } from "./fonts"; // Import Lora and Rubik fonts
import "./globals.css"; // Import global styles

// Set metadata for the site (title and description)
export const metadata: Metadata = {
  title: "Create Next App", // Site title
  description: "Generated by create next app", // Site description
};

// Prevent Zoom In (important for forms)
export const viewport = {
  width: "device-width", // Use the width of the device
  initialScale: 1, // Start at full scale
  maximumScale: 1, // Don't let zooming in
  userScalable: "0", // Disable zooming
};

// RootLayout wraps everything on the site
export default function RootLayout({
  children, // Children are the content inside the layout
}: Readonly<{
  children: React.ReactNode; // React content can be anything
}>) {
  return (
    <html lang="en">
      {" "}
      {/* Set language to English */}
      <body className={`${lora.variable} ${rubik.variable}`}>
        {children}
      </body>{" "}
      {/* Apply Lora and Rubik fonts to body */}
    </html>
  );
}
